#!/usr/bin/env python2
'''
Usage:
    qp_h5_to_ezfio (integrals|bootstrap) <ez> [<h5>] (--ao|--mo)
'''

from __future__ import print_function
from ezfio import ezfio
import h5py
import sys
from docopt import docopt
import os
import subprocess

H5_DEFAULT = 'qp_in.h5'

def populate_ezfio(ezfio_filename, h5_filename):
    ezfio.set_file(ezfio_filename)

    with h5py.File(h5_filename, 'r') as f:

        mo_tot_num = f['MO_basis/mo_tot_num'][()]
        nun_elec_alpha = f['electrons/elec_alpha_num'][()]
        num_elec_beta = f['electrons/elec_beta_num'][()]
        nuclear_repulsion = f['nuclei/nuclear_repulsion'][()]

    ezfio.electrons_elec_alpha_num = nun_elec_alpha
    ezfio.electrons_elec_beta_num = num_elec_beta
   
    nucl_num = 1
    ezfio.set_nuclei_nucl_num(nucl_num)
    ezfio.set_nuclei_nucl_charge([42.]*nucl_num)
    ezfio.set_nuclei_nucl_coord( [ [0.], [0.], [0.] ]*nucl_num )
    ezfio.set_nuclei_nucl_label( ['X'] * nucl_num )

    ezfio.set_nuclei_nuclear_repulsion(nuclear_repulsion)
    ezfio.set_nuclei_disk_access_nuclear_repulsion('Read')

    # Ao num
    ao_num = 1
    ezfio.set_ao_basis_ao_basis("dummy")
    ezfio.set_ao_basis_ao_num(ao_num)
    ezfio.set_ao_basis_ao_nucl([1]*ao_num) #Maybe put a realy incorrect stuff

    # Cannot be smaller than one S
    ao_prim_num_max  = 3
    d = [ [0] *ao_prim_num_max]*ao_num
    ezfio.set_ao_basis_ao_prim_num([ao_prim_num_max]*ao_num)
    ezfio.set_ao_basis_ao_power(d)
    ezfio.set_ao_basis_ao_coef(d)
    ezfio.set_ao_basis_ao_expo(d)

    # Mo coef
    mo_coef =  [0]*mo_tot_num * ao_num
    
    ezfio.set_mo_basis_mo_tot_num(mo_tot_num)
    ezfio.set_mo_basis_mo_coef(mo_coef)

if __name__ == '__main__':
    arguments = docopt(__doc__)

    filename_ezfio = arguments['<ez>']
    filename_h5 =  arguments['<h5>'] if arguments['<h5>'] else H5_DEFAULT

    if arguments['bootstrap']:
        if arguments['--ao']:
            sys.exit('You cannot boostrap from AO. Please submit a pullrequest or contact developers if really needed')
        if arguments['--mo']:
            populate_ezfio(filename_ezfio, filename_h5)
    
    subprocess.check_call('h5_basis_id="%s" h5_int_path="%s" qp_run read %s' % (int(arguments['--ao']), filename_h5, filename_ezfio),
                          shell=True )
    
